import type { ReactNode, ButtonHTMLAttributes, AnchorHTMLAttributes } from "react";
import Link from "next/link";
import { cn } from "@/lib/utils";
import { SparkleIcon } from "@/components/icons";

/* ── Card ───────────────────────────────────────────── */

export function Card({
  children,
  className,
  ink = false,
  lift = false,
}: {
  children: ReactNode;
  className?: string;
  ink?: boolean;
  lift?: boolean;
}) {
  return (
    <div
      className={cn(
        "rounded-[20px] border p-5",
        ink
          ? "border-transparent bg-ink text-cream shadow-[var(--shadow-ink)]"
          : "border-line bg-surface",
        lift && "liftable",
        className,
      )}
    >
      {children}
    </div>
  );
}

/* ── Eyebrow ────────────────────────────────────────── */

export function Eyebrow({
  children,
  className,
  onDark = false,
}: {
  children: ReactNode;
  className?: string;
  onDark?: boolean;
}) {
  return (
    <div className={cn("eyebrow", onDark && "text-gold-bright", className)}>
      {children}
    </div>
  );
}

/* ── Buttons ────────────────────────────────────────── */

type BtnProps = {
  children: ReactNode;
  className?: string;
  variant?: "ember" | "ember-shimmer" | "ink" | "outline" | "ghost";
  size?: "sm" | "md" | "lg";
};

function btnClasses({ variant = "ember", size = "md", className }: Omit<BtnProps, "children">) {
  return cn(
    "pressable inline-flex items-center justify-center gap-2 rounded-full font-ui font-bold",
    size === "sm" && "px-4 py-2 text-[12px]",
    size === "md" && "px-6 py-3 text-[13.5px]",
    size === "lg" && "px-8 py-4 text-[15px]",
    variant === "ember" &&
      "bg-[image:var(--grad-ember)] text-cta-text shadow-[var(--shadow-ember)]",
    variant === "ember-shimmer" &&
      "shimmer-bg text-cta-text shadow-[var(--shadow-ember-lg)]",
    variant === "ink" && "bg-ink text-cream",
    variant === "outline" &&
      "border border-gold-muted bg-transparent text-gold-dark",
    variant === "ghost" && "text-body hover:text-ink",
    className,
  );
}

export function Button({
  children,
  className,
  variant,
  size,
  ...rest
}: BtnProps & ButtonHTMLAttributes<HTMLButtonElement>) {
  return (
    <button className={btnClasses({ variant, size, className })} {...rest}>
      {children}
    </button>
  );
}

export function ButtonLink({
  children,
  className,
  variant,
  size,
  href,
  ...rest
}: BtnProps & { href: string } & AnchorHTMLAttributes<HTMLAnchorElement>) {
  return (
    <Link href={href} className={btnClasses({ variant, size, className })} {...rest}>
      {children}
    </Link>
  );
}

/* ── Pill ───────────────────────────────────────────── */

export function Pill({
  children,
  className,
  active = false,
  onDark = false,
}: {
  children: ReactNode;
  className?: string;
  active?: boolean;
  onDark?: boolean;
}) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1.5 rounded-full border px-3 py-1.5 text-[11.5px] font-bold",
        active
          ? "border-transparent bg-ink text-cream"
          : onDark
            ? "border-[rgba(201,161,94,.35)] bg-[rgba(252,248,240,.07)] text-cream-2"
            : "border-line-btn bg-surface text-body",
        className,
      )}
    >
      {children}
    </span>
  );
}

/* ── Avatar ─────────────────────────────────────────── */

export function Avatar({
  label,
  size = 38,
  className,
}: {
  label: string;
  size?: number;
  className?: string;
}) {
  return (
    <span
      className={cn(
        "inline-flex shrink-0 items-center justify-center rounded-full bg-ink font-display font-bold text-cream-2",
        className,
      )}
      style={{ width: size, height: size, fontSize: size * 0.38 }}
    >
      {label}
    </span>
  );
}

/* ── AI disclosure (mandatory on every AI surface) ──── */

export function AiDisclosure({
  className,
  onDark = false,
}: {
  className?: string;
  onDark?: boolean;
}) {
  return (
    <p
      className={cn(
        "flex items-center gap-1.5 text-[10.5px] font-semibold",
        onDark ? "text-[rgba(232,220,196,.62)]" : "text-faint",
        className,
      )}
    >
      <SparkleIcon size={10} className={onDark ? "text-gold-bright" : "text-gold"} />
      Generated by AI Planner · trained by our astrologers
    </p>
  );
}

/* ── Stat mini-card ─────────────────────────────────── */

export function Stat({
  label,
  value,
  sub,
  className,
  children,
}: {
  label: string;
  value: ReactNode;
  sub?: string;
  className?: string;
  children?: ReactNode;
}) {
  return (
    <div className={cn("rounded-[18px] border border-line bg-surface p-4", className)}>
      <div className="text-[9.5px] font-bold uppercase tracking-[2px] text-gold">
        {label}
      </div>
      <div className="mt-1.5 flex items-center gap-2 font-display text-[17px] font-bold text-ink">
        {value}
        {children}
      </div>
      {sub ? <div className="mt-0.5 text-[11px] text-muted">{sub}</div> : null}
    </div>
  );
}

/* ── Divider ────────────────────────────────────────── */

export function Divider({ className }: { className?: string }) {
  return <hr className={cn("border-t border-line-soft", className)} />;
}
